
FROM dpage/pgadmin4

# Installer les dépendances nécessaires
RUN apk update && apk add --no-cache python3 py3-pip

# Copier le script d'initialisation dans le conteneur
COPY init_pgadmin.py /docker-entrypoint-init.d/init_pgadmin.py

# Installer les dépendances Python requises par le script
RUN pip3 install --no-cache-dir Flask-SQLAlchemy

# Définir les permissions
RUN chmod +x /docker-entrypoint-init.d/init_pgadmin.py